### ISSUE TITLE
Cannot paste the module in the empty section

### ISSUE THREAD

**Issue by volodymyrdovhan** [EduardoKrausME/moodle-local_copy#5]
Hello,
I found an issue when I could not paste the module in the empty section:

![image](https://github.com/user-attachments/assets/28b4fba0-e4db-4a5f-9cc4-13be0fb43242)

**Comment by eduardokraus** [comment]
Note that the `styles.css` file uses only the `.local_copy-paste-content` class. Since it is a local plugin, I cannot start with `.PATH`.
