### ISSUE TITLE
Broken redirect

### ISSUE THREAD

**Issue by volodymyrdovhan** [EduardoKrausME/moodle-local_copy#6]
Hello,
I still have an error with plugin redirects.
I found an issue with cutting the Moodle URL from the redirect URL. After commenting out this code, the redirect works as expected:

![image](https://github.com/user-attachments/assets/ab4bfd97-7508-48a7-b711-fd240c3206a6)
![image](https://github.com/user-attachments/assets/0fbccf5b-7624-4cde-b4b2-0f1fe6131d53)

**Comment by eduardokraus** [comment]
I switched to `new moodle_url`, which provides greater security.
